<?php include __DIR__ . '/header.phtml'; ?>

    <main>
        <div class="container d-flex flex-column align-items-center my-5">
            <form>
        <fieldset class="d-flex flex-column gap-3 border p-3 text-center">
            <legend>Inscription</legend>

            <label>Nom</label>
            <input id="nom" name="nom" required>

            <label>Prénom</label>
                <input id="prenom" name="prenom" required>

            <label>Pseudo</label>
                 <input id="pseudo" name="pseudo" required>

            <label>Email</label> 
                <input id="email" name="email" type="email" required>

            <label>Mot de passe</label>
                 <input id="password" name="password" type="password" required>

            <label>Confirmer</label> 
                <input id="confirm-password" name="confirm-password" type="password" required>

            <label>
                <input id="chauffeur" name="chauffeur" type="checkbox"> Je suis chauffeur</label>

            <button type="submit" class="btn btn-dark">S'inscrire</button>

            <p>Déjà inscrit ? <a href="connexion.php">Se connecter</a></p>

            </fieldset>
        </form>
        </div>    
    </main>
    
<?php include __DIR__ . '/footer.phtml'; ?>